// <auto-generated />
namespace Web.InterviewAssistant.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createlogdatefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createlogdatefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201701281523580_create logdate field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
