// <auto-generated />
namespace Web.InterviewAssistant.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createlogtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createlogtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701280350290_create log table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
